version: '3.6'

services:
  proxy:
    image: traefik
    ports:
      - "80:80"
    volumes:
      - ../config/traefik.toml:/etc/traefik/traefik.toml:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      default:
        aliases:
          - qybit.com
          - auth.qybit.com
          - ws.slanger.qybit.com
          - api.slanger.qybit.com
          - pma.qybit.com
          - monitor.qybit.com
    labels:
      traefik.enable: true
      traefik.frontend.rule: 'Host: monitor.qybit.com'
      traefik.port: 8080
