# List of Barong administrators.
#
# Other parameters that you can set here can be found in Account,
# Profile and Phone models (e.g. app/models/account.rb...); all the
# model properties are listed at the very bottom of this models files.
#
# Note: email is the only required field here.
accounts:
  - account:
      email: admin@barong.io
      password: Qwerty123
      role: admin
      state: active
      level: 3

# List of applications that will use Barong OAuth.
# You can set any Doorkeeper::Application property here.
#
# Note: in production env, `redirect_uri` can only be a 'https' url.
applications:
  - name: "Peatio"
    redirect_uri: "http://qybit.com/auth/barong/callback"
    skipauth: true
    uid: "a68be319fca51caca60eed5711226e568bd1c1d13ff452b945515f1a6ffbaca4"
    secret: "ab80e2c843861c4d23e63f5472cd1c9ee6f55e388863e21f22b03a9093977f29"

levels:
  - key: email
    value: verified
    description: "User clicked on the confirmation link"
  - key: phone
    value: verified
    description: "User entered a valid code from sms"
  - key: document
    value: verified
    description: "User personal documents have been verified"

